ticket-31: Create training inputs
AllenInstitute/DeepCell pull request #32
Opened 2022-04-22 17:59 UTC by morriscb

2022-04-25 15:23 UTC, aamster requested changes

2022-04-25 20:14 UTC, morriscb commented on src/deepcell/cli/modules/create_train_test_split.py
> +            for roi_idx in range(len(roi_data[0])):
Sounds good. Figured there was potentially enforced ordering from the app but if not I can be more careful with these checks.

2022-04-25 20:19 UTC, morriscb commented on tests/cli/modules/test_create_train_test_split.py
> +                roi['label'] == 'cell'
Sorry, missed putting in the assert.

2022-04-25 23:21 UTC, morriscb commented on src/deepcell/cli/modules/create_train_test_split.py
> +            for roi_idx in range(len(roi_data[0])):
Finished up changing the logic here. Now I load the ROI data from json into a DataFrame indexed by `roi_id`.

2022-04-26 13:22 UTC, aamster approved these changes
Please address the remaining comments. Otherwise looks good.

2022-04-26 13:22 UTC, aamster commented on src/deepcell/cli/modules/create_train_test_split.py
> +                n_votes = 0
This variable not needed anymore

2022-04-26 13:22 UTC, aamster commented on src/deepcell/cli/modules/create_train_test_split.py
> +                # Count the number of votes for "cell". If the percentage
Please remove this doc; it's not needed anymore since this has been modularized

2022-04-26 13:22 UTC, aamster commented on src/deepcell/cli/modules/create_train_test_split.py
> +        """Loop through labels for a given roi_id and return if they were
That's not actually what this method is doing; it is returning a final label given multiple labeler's votes for a given roi

2022-04-26 18:51 UTC, morriscb commented
Hey, had to fix up how the experiment metadata gets ingested. Check out the changes in `get_experiment_metadata`. That's the simplest solution I came up with without adding a significant number of unused and optional parameters to the experiment_metadata schema. Let me know if you're happy with this or if I should add all the unused columns to the schema.

2022-04-26 18:59 UTC, aamster commented on src/deepcell/datasets/model_input.py
>          """Instantiate a ModelInput from a data_dir
@morriscb please also remove the "This should be used at test time", since you are using it to build training examples with labels

2022-04-26 18:59 UTC, aamster commented
@morriscb that solution looks fine

2022-04-26 19:49 UTC, merged